"""Web Push: a plan change reaches the phone even with a dark screen.

The live view reports a change by itself - but only while it is open and the
screen is on. Someone who has put the phone in their pocket would otherwise
only find out at the charger that the plan is a different one. That is what
Web Push is for: the server sends the message to the browser's push service
(Google, Mozilla, Apple), which delivers it to the device.

**Without a VAPID key the feature is off.** That is the same attitude as with
`ORS_API_KEY` and `APP_PASSWORT`: what is not set up is not faked - it is in
the log at startup and the interface says so as well. Keys are generated by
`tools/push_keyname.py`.

Two things that are deliberately the way they are:

- **Sending is injectable** (`dispatcher`). The encryption, the choice of
  recipients and the cleaning up of dead subscriptions can thus be checked
  completely without reaching a push service - see tools/check_push.py. Only
  the network hop itself remains untested, and it does not belong in a check
  script either.
- **A dead subscription is deleted, no other error.** A browser that has
  revoked the permission answers with 404 or 410; the subscription is then
  permanently worthless. A timeout or a 500 from the push service, on the
  other hand, says nothing about the subscription - whoever throws it away
  for that switches off the notifications permanently at the first
  disruption.
"""
import base64
import json
import logging
import os
import ipaddress
import socket
import threading
from urllib.parse import urlsplit

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec

from . import models

log = logging.getLogger("uvicorn.error")

# How long to wait for the push service. The message is relevant on the road
# or not at all; a call that hangs for a minute helps nobody and ties up a
# thread.
TIME_LIMIT_S = 10

# Responses after which a subscription is gone for good.
TOT = (404, 410)


# ---------------------------------------------------------------------------
# Keys
# ---------------------------------------------------------------------------

def _b64(raw_data: bytes) -> str:
    return base64.urlsafe_b64encode(raw_data).rstrip(b"=").decode("ascii")


def generate_key() -> tuple[str, str]:
    """A new VAPID key pair: (private, public), both base64url.

    The public key is the uncompressed point (65 bytes) - exactly the format
    the browser expects as `applicationServerKey`.
    """
    private_ = ec.generate_private_key(ec.SECP256R1())
    raw_private_ = private_.private_numbers().private_value.to_bytes(32, "big")
    raw_public_ = private_.public_key().public_bytes(
        serialization.Encoding.X962, serialization.PublicFormat.UncompressedPoint)
    return _b64(raw_private_), _b64(raw_public_)


def private_key() -> str:
    return os.environ.get("VAPID_PRIVATE_KEY", "").strip()


def pub_key() -> str:
    return os.environ.get("VAPID_PUBLIC_KEY", "").strip()


def sender() -> str:
    """The `sub` claim of the VAPID assertion.

    The push service wants to know whom it can reach if a server becomes
    conspicuous. A mailto: or https: address, otherwise some services refuse.
    """
    value = os.environ.get("VAPID_SUBJECT", "").strip()
    return value or "mailto:jolt@localhost"


def actual_configured() -> bool:
    return bool(private_key() and pub_key())


def at_start_warn() -> None:
    if not actual_configured():
        log.info("No VAPID key set - notifications to the phone are off. "
                 "Generate keys: tools/push_keyname.py")


# ---------------------------------------------------------------------------
# Subscriptions
# ---------------------------------------------------------------------------

def save_subscription(db, endpoint: str, p256dh: str, auth: str,
                  device: str = "") -> models.PushSubscription:
    """Create or refresh a subscription.

    Idempotent via the endpoint: the browser delivers the same one on every
    call as long as the permission exists. A second call is meant to renew the
    subscription and not duplicate it - otherwise the same phone would get the
    notification several times.
    """
    subscription = db.query(models.PushSubscription).filter_by(endpoint=endpoint).one_or_none()
    if subscription is None:
        subscription = models.PushSubscription(endpoint=endpoint)
        db.add(subscription)
    subscription.p256dh = p256dh
    subscription.auth = auth
    subscription.device = (device or "")[:120]
    subscription.failure = 0
    db.commit()
    return subscription


def delete_subscription(db, endpoint: str) -> bool:
    subscription = db.query(models.PushSubscription).filter_by(endpoint=endpoint).one_or_none()
    if subscription is None:
        return False
    db.delete(subscription)
    db.commit()
    return True


def _as_subscription(subscription: models.PushSubscription) -> dict:
    """Bring it into the form that pywebpush expects."""
    return {"endpoint": subscription.endpoint,
            "keys": {"p256dh": subscription.p256dh, "auth": subscription.auth}}


# ---------------------------------------------------------------------------
# Sending
# ---------------------------------------------------------------------------

def endpoint_allowed(endpoint: str) -> bool:
    """Whether the server may call this address as a push service.

    The endpoint comes from the browser, i.e. from anyone with access - and the
    server later calls it itself (SSRF). Therefore: https only, and the name
    must point to public addresses. Loopback, private networks, link-local
    (cloud metadata 169.254.169.254) and the Docker names such as `db` are
    thereby excluded. Not resolvable means rejected.
    """
    try:
        parts = urlsplit(endpoint)
        host = parts.hostname
        if parts.scheme != "https" or not host or parts.username or parts.password:
            return False
        addresses = {a[4][0] for a in socket.getaddrinfo(host, parts.port or 443,
                                                        proto=socket.IPPROTO_TCP)}
    except (ValueError, OSError):
        return False
    if not addresses:
        return False
    return all(ipaddress.ip_address(a.split("%")[0]).is_global for a in addresses)


def _send_real(subscription: models.PushSubscription, message: bytes) -> int:
    """The actual sending to the push service. Returns the HTTP status."""
    from pywebpush import WebPushException, webpush

    # Check when sending too: an old subscription or a name that now points
    # somewhere else must not send the server into its own network.
    if not endpoint_allowed(subscription.endpoint):
        return 0
    try:
        response = webpush(
            subscription_info=_as_subscription(subscription), data=message,
            vapid_private_key=private_key(),
            vapid_claims={"sub": sender()},
            content_encoding="aes128gcm", timeout=TIME_LIMIT_S)
        return getattr(response, "status_code", 201)
    except WebPushException as failure:
        response = getattr(failure, "response", None)
        # Without a response it is a network problem, no verdict on the subscription.
        return getattr(response, "status_code", 0) if response is not None else 0


def send(db, title: str, text: str, url: str = "/", dispatcher=None) -> dict:
    """A notification to all subscriptions. Cleans up dead ones in the process.

    `dispatcher(subscription, message) -> HTTP status` can be replaced; that
    way selection, payload and clean-up can be checked without reaching a
    push service.
    """
    if dispatcher is None:
        if not actual_configured():
            return {"sent": 0, "removed": 0, "failure": 0, "skipped": True}
        dispatcher = _send_real

    message = json.dumps({"title": title, "text": text, "url": url},
                           ensure_ascii=False).encode("utf-8")

    sent = failure = 0
    tot: list[models.PushSubscription] = []
    for subscription in db.query(models.PushSubscription).all():
        try:
            status = dispatcher(subscription, message)
        except Exception as exception:      # noqa: BLE001
            log.warning("Push to %s failed: %s", subscription.endpoint[:60],
                        exception)
            status = 0

        if status in TOT:
            tot.append(subscription)
        elif 200 <= status < 300:
            sent += 1
            subscription.failure = 0
        else:
            failure += 1
            subscription.failure = (subscription.failure or 0) + 1

    for subscription in tot:
        log.info("Push subscription removed (unsubscribed): %s", subscription.endpoint[:60])
        db.delete(subscription)
    db.commit()

    return {"sent": sent, "removed": len(tot), "failure": failure,
            "skipped": False}


def send_background(db_factory, title: str, text: str, url: str = "/") -> None:
    """Like `send`, but without holding up the caller.

    A measurement point comes from a moving car; the response to it must not
    wait for a push service. The thread gets a database session of its own -
    one shared across threads would be exactly the mistake SQLAlchemy does not
    forgive.
    """
    if not actual_configured():
        return

    def cycle():
        db = db_factory()
        try:
            send(db, title, text, url)
        except Exception as failure:      # noqa: BLE001
            log.warning("Push in the background failed: %s", failure)
        finally:
            db.close()

    threading.Thread(target=cycle, daemon=True, name="jolt-push").start()
